### PR TITLE
Outreach playbook

### PR DESCRIPTION
**Pull request by pwalczysko**
The playbook proposed here seems to work for the outreach server. 
To test:

  - check that the structure of the folders and the playbook itself makes sense (maybe the playbook should not be in the subfolder ``public-user``, and should be called differently
  - the disussion with @joshmoore suggested that this repo is just a temporary stage for this playbook (?)
 
cc @manics @jburel @joshmoore

### CODE REVIEW

**Comment by pwalczysko** [comment]
https://github.com/openmicroscopy/ansible-role-omero-server/issues/21 is the fix

**Comment by kennethgillen** [comment]
Is it time to split this into a MT PR and a prod-playbooks PR? 

cc @joshmoore

**Comment by joshmoore** [comment]
NB: restarted travis to see if the following failure goes away:

```
[0m=================================== FAILURES ===================================[0m
[0m[1m[31m_________________ test_omero_web_public[docker://omero-server] _________________[0m[0m
[0m[0m
[0mCommand = <command>[0m
[0m[0m
[0m[1m    def test_omero_web_public(Command):[0m[0m
[0m[1m        out = Command.check_output([0m[0m
[0m[1m            'curl -f http://localhost/webclient/api/containers/')[0m[0m
[0m[1m>       r = json.loads(out)[0m[0m
[0m[0m
[0m[1m[31mtests/test_default.py[0m:13:[0m
[0m_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _[0m
[0m[1m[31m/opt/python/2.7.14/lib/python2.7/json/__init__.py[0m:339: in loads[0m
[0m[1m    return _default_decoder.decode(s)[0m[0m
[0m[1m[31m/opt/python/2.7.14/lib/python2.7/json/decoder.py[0m:364: in decode[0m
[0m[1m    obj, end = self.raw_decode(s, idx=_w(s, 0).end())[0m[0m
[0m_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _[0m
[0m[0m
[0mself = <json.decoder.JSONDecoder object at 0x7fce716068d0>, s = '', idx = 0[0m
[0m[0m
[0m[1m    def raw_decode(self, s, idx=0):[0m[0m
[0m[1m        """Decode a JSON document from ``s`` (a ``str`` or ``unicode``[0m[0m
[0m[1m            beginning with a JSON document) and return a 2-tuple of the Python[0m[0m
[0m[1m            representation and the index in ``s`` where the document ended.[0m[0m
[0m[1m    [0m[0m
[0m[1m            This can be used to decode a JSON document from a string that may[0m[0m
[0m[1m            have extraneous data at the end.[0m[0m
[0m[1m    [0m[0m
[0m[1m            """[0m[0m
[0m[1m        try:[0m[0m
[0m[1m            obj, end = self.scan_once(s, idx)[0m[0m
[0m[1m        except StopIteration:[0m[0m
[0m[1m>           raise ValueError("No JSON object could be decoded")[0m[0m
[0m[1m[31mE           ValueError: No JSON object could be decoded[0m[0m
```

**Comment by joshmoore** [comment]
@kennethgillen : Sorry, I lost track of the fact that this was still ongoing. Considering this is still on public-user, we should certainly discuss the next steps.

**Comment by joshmoore** [comment]
Closing this in favor of:

 * https://github.com/ome/ansible-examples-omero/pull/11
 * https://github.com/openmicroscopy/prod-playbooks/pull/26

**Pull request closed without merging**
